-- =============================================================================
-- Vitalé — Post-companion 0117: autovacuum tuning for hot partitioned tables
-- Ground truth: VITALE_IMPLEMENTATION_SPEC Part 10 §Phase 10.
--
-- Write-heavy partitioned tables receive lower autovacuum scale factors so
-- dead-tuple bloat is reclaimed promptly.
--
-- SUBSTRATE NOTE (vanilla PG / standard PG): a PARTITIONED parent CANNOT hold
-- storage parameters — `ALTER TABLE <partitioned> SET (autovacuum_*)` raises
-- "cannot specify storage parameters for a partitioned table", and a parent's
-- reloptions are NOT inherited by partitions anyway. Per-partition tuning is
-- therefore applied two ways:
--   (a) FUTURE partitions: registered in public.part_config.child_reloptions so
--       ensure_month_partition (0000) applies them to each new child at creation.
--   (b) EXISTING partitions: ALTERed directly below via pg_partition_tree leaves.
-- coach_data_access_audit is provisioned outside the part_config maintenance
-- loop (0113), so only path (b) covers it; its yearly/monthly window is fixed.
--
-- Apply order: after 0116 (lexical). Idempotent: UPDATE + ALTER TABLE SET (...)
-- are safe to re-run.
-- =============================================================================

-- ============================================================================
-- SECTION 1 — high-write partitioned parents (per-partition autovacuum tuning)
-- ============================================================================

-- (a) Register child reloptions so FUTURE partitions are born tuned.
--     health_observations: frequent coach + patient writes (30 s cadence)
--     nutrition_logs:       meal-logging cadence — up to 3x/day per user
--     messages:             chat — potentially 100s/day for active orgs
--     notifications:        high-fan-out; generated by multiple trigger paths
UPDATE public.part_config
   SET child_reloptions =
       'autovacuum_vacuum_scale_factor=0.01,autovacuum_analyze_scale_factor=0.005,autovacuum_vacuum_cost_delay=2'
 WHERE parent_table IN ('health_observations','nutrition_logs','messages','notifications');

-- (b) Apply to EXISTING leaf partitions now (pg_partition_tree handles any depth).
DO $av$
DECLARE r record;
BEGIN
  -- standard high-write profile
  FOR r IN
    SELECT pt.relid::regclass AS child
      FROM unnest(ARRAY['public.health_observations','public.nutrition_logs',
                        'public.messages','public.notifications']::regclass[]) AS parent
      CROSS JOIN LATERAL pg_partition_tree(parent) pt
     WHERE pt.isleaf
  LOOP
    EXECUTE format(
      'ALTER TABLE %s SET (autovacuum_vacuum_scale_factor=0.01, '
      || 'autovacuum_analyze_scale_factor=0.005, autovacuum_vacuum_cost_delay=2)', r.child);
  END LOOP;

  -- coach_data_access_audit: INSERT-heavy but IMMUT-BLOCKed (no UPDATE/DELETE
  -- dead tuples) — tune analyze cadence + cost_delay only.
  FOR r IN
    SELECT pt.relid::regclass AS child
      FROM pg_partition_tree('public.coach_data_access_audit'::regclass) pt
     WHERE pt.isleaf
  LOOP
    EXECUTE format(
      'ALTER TABLE %s SET (autovacuum_analyze_scale_factor=0.01, '
      || 'autovacuum_vacuum_cost_delay=5)', r.child);
  END LOOP;
END
$av$;

-- ============================================================================
-- SECTION 2 — moderate-write non-partitioned tables
-- ============================================================================

-- access_grants: revoke/expire cycles generate dead tuples
ALTER TABLE public.access_grants SET (
  autovacuum_vacuum_scale_factor  = 0.02,
  autovacuum_analyze_scale_factor = 0.01
);

-- community_posts: likes/flag counters updated in-place frequently
ALTER TABLE public.community_posts SET (
  autovacuum_vacuum_scale_factor  = 0.02,
  autovacuum_analyze_scale_factor = 0.01
);

-- user_streaks: updated nightly in bulk by streak_rollover job
ALTER TABLE public.user_streaks SET (
  autovacuum_vacuum_scale_factor  = 0.02,
  autovacuum_analyze_scale_factor = 0.01
);

-- leaderboard_scores: bulk-recomputed by streak_rollover job
ALTER TABLE public.leaderboard_scores SET (
  autovacuum_vacuum_scale_factor  = 0.02,
  autovacuum_analyze_scale_factor = 0.01
);

-- ============================================================================
-- NOTES
-- • Scale factor 0.01 = trigger vacuum after 1% of table rows are dead.
--   Default is 0.20 (20%) — too slow for hot partitioned tables.
-- • cost_delay = 2ms (default 20ms) lets autovacuum run faster on hot tables.
-- • Partition-level overrides: add ALTER TABLE on specific partitions if a
--   single month's partition is exceptionally hot.
-- • These settings are advisory for query planning but also affect bloat;
--   monitor pg_stat_user_tables.n_dead_tup on these tables post-launch.
-- =============================================================================
